Repository AY2324S2-CS2113-T11-2/tp, pull requests merged in 2024-03, with the labels that each got.

#16 Sean dooa generate itinerary j unit test
  src/main/java/seedu/duke/GenerateItineraryCommand.java
  src/main/java/seedu/duke/Itinerary.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, type.Task

#28 Implement JUnit Test for Parser Class
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High, type.Task

#30 Database access issue resolved
  META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/resources/ActivityList.txt
  src/main/resources/FoodList.txt
  src/test/java/seedu/duke/DukeTest.java
Labels: type.Bug, priority.High

#33 Add function for user to key in personal data
  .vscode/settings.json
  data/UserDetails.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserDetails.java
  src/main/java/seedu/duke/UserDetailsCommand.java
Labels: priority.Medium, type.Task

#39 Add function to generate Smart Itinerary
  src/main/java/seedu/duke/AddFoodCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Food.java
  src/main/java/seedu/duke/FoodList.java
  src/main/java/seedu/duke/GenerateSmartItineraryCommand.java
  src/main/java/seedu/duke/ListOptionsCommand.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserDetails.java
  src/main/java/seedu/duke/UserDetailsCommand.java
  src/main/resources/FoodList.txt
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Story

#41 Add Smart Itinerary feature to Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#46 Sean dooa anniversary reminders
  build.gradle
  data/UserDetails.txt
  src/main/java/seedu/duke/AddActivityCommand.java
  src/main/java/seedu/duke/AddFoodCommand.java
  src/main/java/seedu/duke/Command.java
  src/main/java/seedu/duke/DeleteFavouritesCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ExitCommand.java
  src/main/java/seedu/duke/FindFavouritesCommand.java
  src/main/java/seedu/duke/GenerateIdeaCommand.java
  src/main/java/seedu/duke/GenerateItineraryCommand.java
  src/main/java/seedu/duke/GenerateSmartItineraryCommand.java
  src/main/java/seedu/duke/HelpCommand.java
  src/main/java/seedu/duke/ListFavouritesCommand.java
  src/main/java/seedu/duke/ListOptionsCommand.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/UserDetails.java
  src/main/java/seedu/duke/UserDetailsCommand.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Story, priority.High

#47 Update input parameters for ViewHistoryCommand
  src/main/java/seedu/duke/ViewHistoryCommand.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High

#50 Add GiftList and view history of gifts
  src/main/java/seedu/duke/GenerateGiftCommand.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/ViewHistoryCommand.java
  src/main/resources/ActivityList.txt
  src/main/resources/FoodList.txt
  src/main/resources/GiftList.txt
Labels: type.Enhancement, priority.Medium

#51 Add assertion and log
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/resources/GiftList.txt
Labels: documentation, priority.High, type.Task

#52 Update user guide for command usage
  docs/UserGuide.md
  src/main/java/seedu/duke/GenerateGiftCommand.java
  src/main/java/seedu/duke/Ui.java
Labels: documentation, type.Task

#53 Add JavaDoc comments
  data/UserDetails.txt
  src/main/java/seedu/duke/GenerateSmartItineraryCommand.java
  src/main/java/seedu/duke/UserDetails.java
  src/main/java/seedu/duke/UserDetailsCommand.java
Labels: documentation

#55 Repackage command classes into commands package
  src/main/java/seedu/duke/Activity.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Food.java
  src/main/java/seedu/duke/Gift.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/AddActivityCommand.java
  src/main/java/seedu/duke/commands/AddFoodCommand.java
  src/main/java/seedu/duke/commands/DeleteFavouritesCommand.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/FindFavouritesCommand.java
  src/main/java/seedu/duke/commands/GenerateGiftCommand.java
  src/main/java/seedu/duke/commands/GenerateIdeaCommand.java
  src/main/java/seedu/duke/commands/GenerateItineraryCommand.java
  src/main/java/seedu/duke/commands/GenerateSmartItineraryCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/ListFavouritesCommand.java
  src/main/java/seedu/duke/commands/ListOptionsCommand.java
  src/main/java/seedu/duke/commands/UserDetailsCommand.java
  src/main/java/seedu/duke/commands/ViewHistoryCommand.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.Medium, type.Task

#58 Update Developer Guide for Gift Feature
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#57 Sean dooa generate idea developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/GenerateIdeaCommand.java
Labels: documentation, priority.High

#59 Add activity diagram for GenerateIdeaCommand
  docs/DeveloperGuide.md
  docs/diagrams/GenerateIdeaActivityDiagram.puml
  docs/diagrams/Style.puml
  docs/images/GenerateIdeaActivityDiagram.png
Labels: documentation, priority.High
