Repository AY2324S2-CS2113-T11-2/tp, pull requests merged in 2024-04, with the labels that each got.

#71 Add Sequence Diagram for Smart Itinerary Generation in Developer Guide
  data/UserDetails.txt
  docs/DeveloperGuide.md
  docs/images/GenerateSmartItineraryCommandSequenceDiagram.png
Labels: documentation, priority.High

#73 Improve error handling and testing for ListOptionsCommand
  src/main/java/seedu/duke/commands/ListOptionsCommand.java
  src/test/java/seedu/duke/commands/ListOptionsCommandTest.java
Labels: priority.High, type.Task

#76 Improve error handling for UserDetailsCommand
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/UserDetailsCommand.java
Labels: priority.High, type.Task

#78 Improve error handling for GenerateIdeaCommand
  src/main/java/seedu/duke/Idea.java
  src/main/java/seedu/duke/commands/GenerateIdeaCommand.java
  src/main/java/seedu/duke/commands/UserDetailsCommand.java
  src/main/resources/ActivityList.txt
  src/main/resources/FoodList.txt
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.Medium, type.Task

#79 Add more expected outputs in User Guide
  docs/UserGuide.md
Labels: documentation, priority.High

#81 Add User Details Collection feature to Developer Guide
  docs/DeveloperGuide.md
  docs/images/UserDetailsCommandSequenceDiagram.png
Labels: documentation, priority.High

#83 Add UML diagram to Gift
  docs/DeveloperGuide.md
  docs/diagrams/GiftClassDiagram.puml
  docs/diagrams/GiftSequenceDiagram.puml
  docs/images/GiftClassDiagram.png
  docs/images/GiftSequenceDiagram.png
Labels: documentation, priority.High

#85 Add termination for generate idea
  src/main/java/seedu/duke/commands/GenerateIdeaCommand.java
Labels: type.Enhancement

#132 Fix bugs and improve checks for User Details inputs
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/commands/UserDetailsCommand.java
Labels: priority.Medium

#133 Fix bugs in User Guide and improve Error Handling for Exit, Help and Smart commands.
  data/UserDetails.txt
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
Labels: type.Bug, documentation, priority.Medium

#137 Fix smart command error message
  data/FlirtFork.txt
  data/UserDetails.txt
  src/main/java/seedu/duke/commands/GenerateSmartItineraryCommand.java
Labels: type.Bug

#139 Improve smart command
  src/main/java/seedu/duke/commands/GenerateSmartItineraryCommand.java
  src/main/resources/FoodList.txt
Labels: priority.Medium

#145 Add to FoodList.txt and Improve Smart Command
  src/main/java/seedu/duke/ActivityList.java
  src/main/java/seedu/duke/SmartItinerary.java
  src/main/java/seedu/duke/commands/GenerateSmartItineraryCommand.java
  src/main/resources/ActivityList.txt
  src/main/resources/FoodList.txt
Labels: type.Bug, priority.Medium

#154 Edit smart command portion in User Guide
  docs/UserGuide.md
Labels: documentation

#156 Add Q&A section and legend for cuisine in User Guide
  docs/UserGuide.md
Labels: documentation, priority.Medium

#157 Add lines to FAQ section
  docs/UserGuide.md
Labels: documentation

#164 Edit GenerateIdeaCommand sequence diagram based on DG review
  docs/diagrams/GenerateIdeaCommandSequenceDiagram.puml
  docs/images/GenerateIdeaCommandSequenceDiagram.png
Labels: documentation, priority.High

#169 Add error handling for anniversary date input
  docs/UserGuide.md
  src/main/java/seedu/flirtfork/Ui.java
  src/main/java/seedu/flirtfork/commands/UserDetailsCommand.java
  src/test/java/seedu/flirtfork/UiTest.java
Labels: priority.Medium, type.Task

#171 First draft for PPP
  docs/team/liuy1103.md
Labels: type.Task

#172 Update Soong En PPP
  docs/team/soongensayo.md
Labels: documentation

#173 Yiting gender specific gift
  data/GiftList.txt
  src/main/java/seedu/flirtfork/Gift.java
  src/main/java/seedu/flirtfork/GiftList.java
  src/main/java/seedu/flirtfork/Parser.java
  src/main/java/seedu/flirtfork/Storage.java
  src/main/java/seedu/flirtfork/Ui.java
  src/main/java/seedu/flirtfork/commands/GenerateGiftCommand.java
  src/main/resources/GiftList.txt
Labels: type.Enhancement, priority.Medium

#176 Add PPP draft for Sean
  docs/AboutUs.md
  docs/team/seandooa.md
Labels: documentation, priority.High

#177 Update Soong En PPP
  docs/AboutUs.md
  docs/team/soongensayo.md
Labels: documentation

#183 Update PPP draft 2
  docs/team/liuy1103.md
Labels: type.Task

#187 Update user guide for gift feature
  docs/UserGuide.md
  src/main/java/seedu/flirtfork/commands/GenerateGiftCommand.java
Labels: documentation

#188 Refactor ListOptionCommand to enable continuous listing until cancel
  docs/UserGuide.md
  src/main/java/seedu/flirtfork/Parser.java
  src/main/java/seedu/flirtfork/Ui.java
  src/main/java/seedu/flirtfork/commands/ListOptionsCommand.java
  src/test/java/seedu/flirtfork/commands/ListOptionsCommandTest.java
Labels: documentation, type.Enhancement

#189 Update Sequence Diagrams
  docs/diagrams/GenerateSmartCommandSequenceDiagram.puml
  docs/diagrams/UserDetailsCommandSequenceDiagram.puml
  docs/images/GenerateSmartItineraryCommandSequenceDiagram.png
  docs/images/UserDetailsCommandSequenceDiagram.png
Labels: documentation

#190 Add Object Diagram for UserDetails
  data/ActivityList.txt
  data/FoodList.txt
  data/UserDetails.txt
  docs/DeveloperGuide.md
  docs/diagrams/UserDetailsObjectDiagram.puml
  docs/images/UserDetailsObjectDiagram.png
Labels: documentation

#193 Modify gift generation to prevent repeated randomisation
  src/main/java/seedu/flirtfork/GiftList.java
  src/main/java/seedu/flirtfork/commands/GenerateGiftCommand.java
Labels: type.Bug, priority.High

#197 Add JavaDoc for gift related classes
  src/main/java/seedu/flirtfork/Command.java
  src/main/java/seedu/flirtfork/FlirtFork.java
  src/main/java/seedu/flirtfork/Gift.java
  src/main/java/seedu/flirtfork/GiftList.java
  src/main/java/seedu/flirtfork/Parser.java
  src/main/java/seedu/flirtfork/Storage.java
  src/main/java/seedu/flirtfork/Ui.java
  src/main/java/seedu/flirtfork/commands/ExitCommand.java
  src/main/java/seedu/flirtfork/commands/GenerateGiftCommand.java
  src/main/java/seedu/flirtfork/commands/ListOptionsCommand.java
Labels: documentation

#201 Add more JUnit tests for Parser class
  src/test/java/seedu/flirtfork/ParserTest.java
Labels: priority.Medium, type.Task

#202 Add JUnit test for UI class
  src/test/java/seedu/flirtfork/ParserTest.java
  src/test/java/seedu/flirtfork/UiTest.java
Labels: priority.Medium, type.Task

#204 Yiting ug dg update
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/GiftClassDiagram.puml
  docs/diagrams/GiftSequenceDiagram.puml
  docs/images/GiftClassDiagram.png
  docs/images/GiftSequenceDiagram.png
  src/main/java/seedu/flirtfork/GiftList.java
Labels: documentation

#206 Update PPP draft 3
  docs/team/liuy1103.md
Labels: type.Task

#209 Update PPP to include new community involvements
  docs/team/liuy1103.md
Labels: type.Task

#211 Fix bugs related to inputting anniversary date
  docs/UserGuide.md
  docs/team/seandooa.md
  src/main/java/seedu/flirtfork/Ui.java
Labels: type.Bug, priority.High

#242 Edit User Guide
  docs/UserGuide.md
Labels: documentation

#247 Edit sequence diagram for user details collection
  docs/diagrams/UserDetailsCommandSequenceDiagram.puml
  docs/images/UserDetailsCommandSequenceDiagram.png
Labels: documentation

#248 Edit Soong En PPP
  docs/team/soongensayo.md
Labels: documentation

#250 Fix UG bugs
  data/UserDetails.txt
  docs/UserGuide.md
  docs/team/soongensayo.md
Labels: documentation

#251 Edit Command Summary
  docs/UserGuide.md
Labels: documentation

#255 Add clearer error handlings to parser class
  src/main/java/seedu/flirtfork/Parser.java
Labels: documentation

#257 Add additional line for UG command summary
  docs/UserGuide.md
Labels: type.Bug, documentation

#259 Make integer inputs for user detail fields stricter
  src/main/java/seedu/flirtfork/Ui.java
Labels: type.Bug, priority.High

#261 Attempt to fix broken User Guide hyperlinks
  docs/UserGuide.md
  docs/team/seandooa.md
Labels: documentation, priority.High

#263 Fix features hyperlink
  docs/UserGuide.md
Labels: documentation, priority.High
